#Loading Datasets from Multiple Sources

#Lab Title

Data Ingestion in Data Science using Kaggle, Google Drive, APIs, and Databases (Google Colab Practical)

#Objective

Students will learn how to collect datasets from multiple sources and load them into Python using Google Colab, which is a common workflow in real Data Science projects.

#Libraries Used:
```
pandas

numpy

requests

sqlite3

kaggle

kagglehub
```

#Step 1: Install Required Libraries (Colab Setup)

Run this first in Colab.

In [ ]:
!pip install kaggle kagglehub

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.23)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.5.20)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.5.1)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.10.0)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

#Step 2: Loading Dataset from Kaggle using API
**Upload Kaggle API Key**

Download kaggle.json from Kaggle → Account → Create API Token.

Then upload it in Colab.

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"venkats5385","key":"1048beedef53eb72962e2070a41f6482"}'}

Upload kaggle.json.

#Move API Key to Correct Location

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#Download Dataset

Example: student-performance-data

In [ ]:
!kaggle datasets download -d devansodariya/student-performance-data

Dataset URL: https://www.kaggle.com/datasets/devansodariya/student-performance-data
License(s): CC0-1.0
student-performance-data.zip: Skipping, found more recently modified local copy (use --force to force download)

In [ ]:
!kaggle datasets download -d heptapod/titanic

#Extract Dataset

In [ ]:
import zipfile

with zipfile.ZipFile("student-performance-data.zip", 'r') as zip_ref:
    zip_ref.extractall("dataset")

#Load Dataset

In [ ]:
import pandas as pd

df = pd.read_csv("dataset/student_data.csv")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

#Step 3: Loading Dataset using KaggleHub

In [ ]:
import kagglehub

path = kagglehub.dataset_download("devansodariya/student-performance-data")

print("Dataset downloaded to:", path)

Using Colab cache for faster access to the 'student-performance-data' dataset.
Dataset downloaded to: /kaggle/input/student-performance-data

**Load Dataset**

In [ ]:
df = pd.read_csv(path + "/student_data.csv")
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

#Step 4: Loading Dataset from Google Drive
Mount Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Load Dataset from Drive**

Example path: https://drive.google.com/drive/my-drive

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/student_data.csv')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [ ]:
display(df.describe())

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

#Step 5: Loading Dataset from Public API

Example: Exchange Rate API

In [ ]:
import requests
import pandas as pd

# The user wants to simulate loading student_data from an API.
# Since 'student_data' is not a live public API endpoint, we will simulate
# an API response using the student_data.csv already downloaded locally.

# In a real scenario, 'url' would point to an actual API endpoint for student data.
# url = "https://api.example.com/student_data" # This would be a hypothetical API URL

# For demonstration, we'll load the data from the local file and then
# package it as if it came from an API response.
try:
    # This path refers to the student_data.csv extracted from Kaggle in a previous step
    local_student_data_path = "dataset/student_data.csv"
    # Read the local CSV
    temp_df = pd.read_csv(local_student_data_path)

    # Simulate the JSON structure that an API might return
    # For simplicity, we'll put the DataFrame content directly under a 'data' key
    mock_api_json_response = {"data": temp_df.to_dict(orient='records')}

    # Simulate the processing of an API response
    # In a real API call, 'data' would come from requests.get(url).json()
    # Here, we directly use our mocked JSON.
    api_data_content = mock_api_json_response["data"]

    # Recreate the DataFrame from the "API response"
    df = pd.DataFrame(api_data_content)

except FileNotFoundError:
    print(f"Error: The file '{local_student_data_path}' was not found. "
          "Please ensure the student_data.csv is extracted to the 'dataset' folder.")
    df = pd.DataFrame()
except Exception as e:
    print(f"An error occurred: {e}")
    df = pd.DataFrame()

df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

#Step 6: Loading Dataset from SQL Database

Create sample database.

First, let's establish a connection to our SQLite database.

In [ ]:
import sqlite3

# Create a database connection
conn = sqlite3.connect("student_data.db")
print("Connection to student_data.db established.")

Connection to student_data.db established.

Now, we will create a sample table and insert data into it using the established connection.

In [ ]:
import pandas as pd

data = {
    "student_id":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20],
    "name":['Aarav Sharma','Priya Reddy','Rohit Kumar','Sneha Nair','Venkat','Venu kumar','Veerendra','Prajwal','Shanvitha','Sri','Aarav Sharma','Priya Reddy','Rohit Kumar','Sneha Nair','Venkat','Venu kumar','Veerendra','Prajwal','Shanvitha','Sri'],
    "age":[20,24,21,23,21,25,23,24,21,20,26,27,23,24,21,25,23,24,25,26],
    "gender":['Male','Male','Male','Male','Male','Male','Male','Male','Female','Female','Male','Male','Male','Male','Male','Male','Male','Male','Female','Female'],
    "city":['Hyderabad','Pune','Delhi','Bangalore','Mumbai','Chennai','Kolkata','Hyderabad','Pune','Delhi','Bangalore','Mumbai','Chennai','Kolkata','Delhi','Bangalore','Mumbai','Chennai','Kolkata','Hyderabad'],
    "course":['Computer Science','Data Science','Electronics','Computer Science','Mechanical','Computer Science','Data Science','Electronics','Computer Science','Mechanical','Computer Science','Data Science','Electronics','Computer Science','Mechanical','Computer Science','Data Science','Electronics','Computer Science','Mechanical',],
    "marks_math":[88,91,76,95,89,88,79,83,77,86,80,89,69,78,87,89,90,76,93,79],
    "marks_science":[88,79,83,77,86,80,89,69,78,87,89,90,88,91,76,95,89,88,79,83],
    "marks_english":[78,87,89,90,76,93,79,79,83,77,86,80,89,69,78,87,89,90,88,79],
    "attendance_percent":[92.5,95.0,78.0,88.5,65.0,97.0,72.0,90.0,60.5,70.0,78.0,88.5,65.0,97.0,72.0,90.0,60.5,95.0,78.0,88.5],
    "fee_paid":[45000,50000,38000,42000,45000,40000,38000,42000,50000,45000,38000,42000,45000,40000,38000,42000,50000,45000,50000,38000],
    "enrollment_date":['2023-07-01','2023-07-02','2023-07-01','2023-07-04','2023-07-05','2023-07-06','2023-07-02','2023-07-04','2023-07-01','2023-07-02','2023-07-02','2023-07-01','2023-07-04','2023-07-05','2023-07-06','2023-07-02','2023-07-04','2023-07-01','2023-07-01','2023-07-04']
}

df = pd.DataFrame(data)

df.to_sql("students", conn, if_exists="replace", index=False)
print("Sample 'Students' table created and populated.")

Sample 'Students' table created and populated.

Query Database

In [ ]:
query = "SELECT * FROM students"

df = pd.read_sql(query, conn)
df.head()

,student_id,name,age,gender,city,course,marks_math,marks_science,marks_english,attendance_percent,fee_paid,enrollment_date
0,1,Aarav Sharma,20,Male,Hyderabad,Computer Science,88,88,78,92.5,45000,2023-07-01
1,2,Priya Reddy,24,Male,Pune,Data Science,91,79,87,95.0,50000,2023-07-02
2,3,Rohit Kumar,21,Male,Delhi,Electronics,76,83,89,78.0,38000,2023-07-01
3,4,Sneha Nair,23,Male,Bangalore,Computer Science,95,77,90,88.5,42000,2023-07-04
4,5,Venkat,21,Male,Mumbai,Mechanical,89,86,76,65.0,45000,2023-07-05

#Learning Outcomes

After this practical students will understand:

> How to collect data from multiple sources

> How to authenticate Kaggle API in Colab

> How to load API data for analysis

> How to connect Python with SQL databases

> Real-world data ingestion workflow in Data Science